package com.openbravo.pos.reports;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;
import java.awt.Component;
import java.util.List;

/**
 *
 * @author  adrianromero
 */
public class JParamsComboCapturas extends javax.swing.JPanel implements ReportEditorCreator {
    
    private Datas datasvalue;
    private Formats formatsvalue;
    private QBFCompareEnum comparevalue;
    private SentenceList m_sentcat;
    private ComboBoxValModel m_CategoryModel;
    /** Creates new form JParamsText */
    public JParamsComboCapturas() {
        initComponents();
        
        setLabel(AppLocal.getIntString("label.value"));
        setType(Formats.STRING);
    }
    
    public JParamsComboCapturas(String label) {
        
        initComponents();
        
        setLabel(label);    
        setType(Formats.STRING);
    }
    
    public JParamsComboCapturas(String label, Formats format) {
        
        initComponents();
        
        setLabel(label);    
        setType(format);
    }
    
    public JParamsComboCapturas(String label, Formats format, Datas data) {
        
        initComponents();
        
        setLabel(label);    
        setType(format, data);
    }
    
    public void setLabel(String label) {
        lblField.setText(label);
    }
    
    public void setType(Formats format, Datas data) {
        formatsvalue = format;
        datasvalue = data;
        setDefaultCompare();
    }
    
    public void setType(Formats format) {
        
            setType(format, Datas.STRING);
        
    }
    
    public void setCompare(QBFCompareEnum compare) {
        comparevalue = compare;
    }
    
    private void setDefaultCompare() {
        
             comparevalue = QBFCompareEnum.COMP_EQUALS;
        
    }
    
    public void init(AppView app) {
        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSales");
       
        // El modelo de categorias
        m_sentcat = dlSales.getCapturasList();
        m_CategoryModel = new ComboBoxValModel();
    }

    public void activate() throws BasicException {
        List catlist = m_sentcat.list();
        m_CategoryModel = new ComboBoxValModel(catlist);
        jComboBox1.setModel(m_CategoryModel);
    }
    
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[] {Datas.OBJECT, datasvalue});
    }

    public Component getComponent() {
        return this;
    }
    
    public Object createValue() throws BasicException, NullPointerException {
        try{
        Object value = formatsvalue.parseValue(m_CategoryModel.getSelectedKey().toString());
        //txtField.setText(formatsvalue.formatValue(value));
        
        if (value == null) {        
            return new Object[] {QBFCompareEnum.COMP_NONE, null};
        } else {
            return new Object[] {comparevalue, value};
        }
        }catch(NullPointerException e){
        return new Object[] {QBFCompareEnum.COMP_NONE, null};
        }
    }      
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblField = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(0, 30));
        setLayout(null);

        lblField.setText("***");
        add(lblField);
        lblField.setBounds(20, 10, 120, 14);

        add(jComboBox1);
        jComboBox1.setBounds(140, 10, 300, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblField;
    // End of variables declaration//GEN-END:variables
    
}
